<?php
    /*
        File Name : pageBuilder_moduleConstructor
        Author : David Charles - Add Mustard
        Date created : 25/04/2022
        Description : 
            This script will created the acf fields for the page builder modules
    */

register_field_group(array (
    'id' => 'acf_page-builder-modules-general',
    'title' => 'Page Builder Modules - General',
    'fields' => array (
        array (
            'key' => 'field_PBM_001',
            'label' => 'Page Builder Modules - General',
            'name' => 'page_builder_modules_general',
            'type' => 'flexible_content',
            'layouts' => array (
                /* text block module*/
                array (
                    'label' => 'Text Block Module',
                    'name' => 'textBlock',
                    'display' => 'row',
                    'min' => '',
                    'max' => '',
                    'sub_fields' => array(
                        array (
                            'key' => 'field_textBlock_00',
                            'label' => 'Module - Add Custom ID',
                            'name' => 'customID_include',
                            'type' => 'true_false',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_trueFalse',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'message' => '',
                            'default_value' => 0,
                            'instructions' => 'Select to include a custom ID for this module.',
                        ),
                        array(
                            'key' => 'field_textBlock_0',
                            'label' => 'Custom ID',
                            'name' => 'customID',
                            'type' => 'text',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '#',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                            'instructions' => 'Enter the custom ID name',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_textBlock_00',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_textBlock_1',
                            'label' => 'Text Block Type',
                            'name' => 'textBlock_type',
                            'type' => 'select',
                            'choices' => array (
                                'fullWidth_imageBanner' => 'Text Block in Full Width Image Banner',
                            ),
                            'default_value' => 'fullWidth_imageBanner',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'column_width' => '100%',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_select',
                                'id' => '',
                            ),
                        ),
                        array(
                            'key' => 'field_textBlock_2',
                            'label' => 'Text Block Type - Heading',
                            'name' => 'textBlock_heading',
                            'type' => 'textarea',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_textarea',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'default_value' => '',
                            'placeholder' => 'Please enter heading here.',
                            'prepend' => '',
                            'append' => '',
                            'new_lines' => 'br',
                            'formatting' => 'html',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_textBlock_3',
                            'label' => 'Text Block - Copy',
                            'name' => 'textblock_copy',
                            'type' => 'textarea',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_textarea',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'default_value' => '',
                            'placeholder' => 'Please enter copy here.',
                            'prepend' => '',
                            'append' => '',
                            'new_lines' => 'br',
                            'formatting' => 'html',
                        ),
                        array (
                            'key' => 'field_textBlock_4',
                            'label' => 'Text Block - Add Read More Function',
                            'name' => 'textblock_copy_hasReadMore',
                            'type' => 'true_false',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_trueFalse',
                                'id' => '',
                            ),
                            'column_width' => '100%',
                            'message' => '',
                            'default_value' => 0,
                        ),
                        array (
                            'key' => 'field_textBlock_5',
                            'label' => 'Text Block - Word Count - Desktop',
                            'name' => 'textblock_wordCount_desktop',
                            'type' => 'number',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                'id' => '',
                            ),
                            'column_width' => '33%',
                            'default_value' => '150',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'instructions' => 'Select the word count before the read more on desktop.',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_textBlock_4',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_textBlock_6',
                            'label' => 'Text Block - Word Count - Tablet',
                            'name' => 'textblock_wordCount_tablet',
                            'type' => 'number',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                'id' => '',
                            ),
                            'column_width' => '33%',
                            'default_value' => '100',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'instructions' => 'Select the word count before the read more on tablet.',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_textBlock_4',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_textBlock_7',
                            'label' => 'Text Block - Word Count - Mobile',
                            'name' => 'textblock_wordCount_mobile',
                            'type' => 'number',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                'id' => '',
                            ),
                            'column_width' => '33%',
                            'default_value' => '50',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'instructions' => 'Select the word count before the read more on mobile.',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_textBlock_4',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_textBlock_8',
                            'label' => 'Image - Desktop',
                            'name' => 'image_desktop',
                            'type' => 'image',
                            'column_width' => '50%',
                            'save_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'conditional_logic' => array (
                                array (
                                    array (
                                    'field' => 'field_textBlock_1',
                                    'operator' => '==',
                                    'value' => 'fullWidth_imageBanner',
                                    ),
                                ),
                            )
                        ),
                        array(
                            'key' => 'field_textBlock_9',
                            'label' => 'Image - Mobile',
                            'name' => 'image_mobile',
                            'type' => 'image',
                            'column_width' => '50%',
                            'save_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'conditional_logic' => array (
                                array (
                                    array (
                                    'field' => 'field_textBlock_1',
                                    'operator' => '==',
                                    'value' => 'fullWidth_imageBanner',
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key'               => 'field_textBlock_10',
                            'label'             => 'Image - Overlay Opacity',
                            'name'              => 'image_overlay_opacity',
                            'type'              => 'number',
                            'default_value'     => 0.3,
                            'column_width'      => '100%',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'formatting'        => 'html',
                            'min'               => '0',
                            'max'               => '1',
                            'maxlength'         => '',
                            'wrapper'           => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_number',
                                   'id' => '',
                            ),
                        ),
                    ),
                ),
                /* spacer module */
                array (
                    'label' => 'Spacer Module',
                    'name' => 'spacer_module',
                    'display' => 'row',
                    'min' => '',
                    'max' => '',
                    'sub_fields' => array(
                        array (
                            'key' => 'field_spacer_module_00',
                            'label' => 'Module - Add Custom ID',
                            'name' => 'customID_include',
                            'type' => 'true_false',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_trueFalse',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'message' => '',
                            'default_value' => 0,
                            'instructions' => 'Select to include a custom ID for this module.',
                        ),
                        array(
                            'key' => 'field_spacer_module_0',
                            'label' => 'Custom ID',
                            'name' => 'customID',
                            'type' => 'text',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '#',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                            'instructions' => 'Enter the custom ID name',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_spacer_module_00',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key'               => 'field_spacer_module_1',
                            'label'             => 'Spacer Module Height - Desktop',
                            'name'              => 'spacer_module_height_desktop',
                            'type'              => 'number',
                            'instructions'      => 'Enter the height of the spacer on Desktop.',
                            'default_value'     => 50,
                            'column_width'      => '33%',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => 'px',
                            'formatting'        => 'html',
                            'min'               => '',
                            'max'               => '',
                            'maxlength'         => '',
                            'wrapper'           => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                   'id' => '',
                            ),
                        ),
                        array(
                            'key'               => 'field_spacer_module_2',
                            'label'             => 'Spacer Module Height - Tablet',
                            'name'              => 'spacer_module_height_tablet',
                            'type'              => 'number',
                            'instructions'      => 'Enter the height of the spacer on Tablet.',
                            'default_value'     => 30,
                            'column_width'      => '33%',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => 'px',
                            'formatting'        => 'html',
                            'min'               => '',
                            'max'               => '',
                            'maxlength'         => '',
                            'wrapper'           => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                   'id' => '',
                            ),
                        ),
                        array(
                            'key'               => 'field_spacer_module_3',
                            'label'             => 'Spacer Module Height - Mobile',
                            'name'              => 'spacer_module_height_mobile',
                            'type'              => 'number',
                            'instructions'      => 'Enter the height of the spacer on Mobile.',
                            'default_value'     => 20,
                            'column_width'      => '33%',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => 'px',
                            'formatting'        => 'html',
                            'min'               => '',
                            'max'               => '',
                            'maxlength'         => '',
                            'wrapper'           => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                   'id' => '',
                            ),
                        ),
                    ),
                ),
                /* form module*/
                array (
                    'label' => 'Form Module',
                    'name' => 'form_module',
                    'display' => 'row',
                    'min' => '',
                    'max' => '',
                    'sub_fields' => array(
                        array (
                            'key' => 'field_formModule_00',
                            'label' => 'Module - Add Custom ID',
                            'name' => 'customID_include',
                            'type' => 'true_false',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_trueFalse',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'message' => '',
                            'default_value' => 0,
                            'instructions' => 'Select to include a custom ID for this module.',
                        ),
                        array(
                            'key' => 'field_formModule_0',
                            'label' => 'Custom ID',
                            'name' => 'customID',
                            'type' => 'text',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '#',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                            'instructions' => 'Enter the custom ID name',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_formModule_00',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_formModule_1',
                            'label' => 'Form Module Type',
                            'name' => 'formModule_type',
                            'type' => 'select',
                            'choices' => array (
                                'with_image_left' => 'Form with Image left',
                            ),
                            'default_value' => 'with_image_left',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'column_width' => '100%',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_select',
                                'id' => '',
                            ),
                        ),
                        array(
                            'key' => 'field_formModule_2',
                            'label' => 'Form Module - Heading',
                            'name' => 'formModule_heading',
                            'type' => 'textarea',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_textarea',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'default_value' => '',
                            'placeholder' => 'Please enter heading here.',
                            'prepend' => '',
                            'append' => '',
                            'new_lines' => 'br',
                            'formatting' => 'html',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_formModule_3',
                            'label' => 'Form Module - Copy',
                            'name' => 'formModule_copy',
                            'type' => 'textarea',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_textarea',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'default_value' => '',
                            'placeholder' => 'Please enter copy here.',
                            'prepend' => '',
                            'append' => '',
                            'new_lines' => 'br',
                            'formatting' => 'html',
                        ),
                        array (
                            'key' => 'field_formModule_4',
                            'label' => 'Form Module - Add Read More Function',
                            'name' => 'formModule_copy_hasReadMore',
                            'type' => 'true_false',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_trueFalse',
                                'id' => '',
                            ),
                            'column_width' => '100%',
                            'message' => '',
                            'default_value' => 0,
                        ),
                        array (
                            'key' => 'field_formModule_5',
                            'label' => 'Form Module - Word Count - Desktop',
                            'name' => 'formModule_wordCount_desktop',
                            'type' => 'number',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                'id' => '',
                            ),
                            'column_width' => '33%',
                            'default_value' => '150',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'instructions' => 'Select the word count before the read more on desktop.',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_formModule_4',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_formModule_6',
                            'label' => 'Form Module - Word Count - Tablet',
                            'name' => 'formModule_wordCount_tablet',
                            'type' => 'number',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                'id' => '',
                            ),
                            'column_width' => '33%',
                            'default_value' => '100',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'instructions' => 'Select the word count before the read more on tablet.',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_formModule_4',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_formModule_7',
                            'label' => 'Form Module - Word Count - Mobile',
                            'name' => 'formModule_wordCount_mobile',
                            'type' => 'number',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                'id' => '',
                            ),
                            'column_width' => '33%',
                            'default_value' => '50',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'instructions' => 'Select the word count before the read more on mobile.',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_formModule_4',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_formModule_8',
                            'label' => 'Image - Desktop',
                            'name' => 'image_desktop',
                            'type' => 'image',
                            'column_width' => '50%',
                            'save_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'wrapper'           => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_image',
                                   'id' => '',
                            ),
                            'conditional_logic' => array (
                                array (
                                    array (
                                    'field' => 'field_formModule_1',
                                    'operator' => '==',
                                    'value' => 'with_image_left',
                                    ),
                                ),
                            )
                        ),
                        array(
                            'key' => 'field_formModule_9',
                            'label' => 'Image - Mobile',
                            'name' => 'image_mobile',
                            'type' => 'image',
                            'column_width' => '50%',
                            'save_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'wrapper'           => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_image',
                                   'id' => '',
                            ),
                            'conditional_logic' => array (
                                array (
                                    array (
                                    'field' => 'field_formModule_1',
                                    'operator' => '==',
                                    'value' => 'with_image_left',
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key'               => 'field_formModule_10',
                            'label'             => 'Contact Form 7 Form ID',
                            'name'              => 'formModule_formshortcodeID',
                            'type'              => 'number',
                            'default_value'     => '',
                            'column_width'      => '100%',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'formatting'        => 'html',
                            'min'               => '',
                            'max'               => '',
                            'maxlength'         => '',
                            'wrapper'           => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_number',
                                   'id' => '',
                            ),
                        ),

                    ),
                ),
                /* switch content module */
                array (
                    'label' => 'Switch Content Module',
                    'name' => 'switchContent_module',
                    'display' => 'row',
                    'min' => '',
                    'max' => '',
                    'sub_fields' => array(
                        array (
                            'key' => 'field_switchContent_00',
                            'label' => 'Module - Add Custom ID',
                            'name' => 'customID_include',
                            'type' => 'true_false',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_trueFalse',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'message' => '',
                            'default_value' => 0,
                            'instructions' => 'Select to include a custom ID for this module.',
                        ),
                        array(
                            'key' => 'field_switchContent_0',
                            'label' => 'Custom ID',
                            'name' => 'customID',
                            'type' => 'text',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '#',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                            'instructions' => 'Enter the custom ID name',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_switchContent_00',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_switchContent_1',
                            'label' => 'Switch Conetent - Content Type',
                            'name' => 'switchContent_type',
                            'type' => 'select',
                            'choices' => array (
                                'text_with_carousel' => 'Text Content with Carousel',
                            ),
                            'default_value' => 'text_with_carousel',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'column_width' => '100%',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_select',
                                'id' => '',
                            ),
                        ),
                        array(
                            'key' => 'field_switchContent_2',
                            'label' => 'Switch Content Items',
                            'name' => 'switchContent_text_with_carousel_repeater',
                            'type' => 'repeater',
                            'sub_fields' => array (
                                array(
                                    'key' => 'field_switchContent_3',
                                    'label' => 'Switch Copy',
                                    'name' => 'switch_copy',
                                    'type' => 'text',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_text',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'formatting' => 'html',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_switchContent_4',
                                    'label' => 'Text Content - Heading',
                                    'name' => 'content_header',
                                    'type' => 'textarea',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_text',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '',
                                    'placeholder' => 'Please enter heading here.',
                                    'prepend' => '',
                                    'append' => '',
                                    'new_lines' => 'br',
                                    'formatting' => 'html',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_switchContent_5',
                                    'label' => 'Text Content - Copy',
                                    'name' => 'content_copy',
                                    'type' => 'textarea',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_text',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '',
                                    'placeholder' => 'Please enter copy here.',
                                    'prepend' => '',
                                    'append' => '',
                                    'new_lines' => 'br',
                                    'formatting' => 'html',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_switchContent_6',
                                    'label' => 'Text Content - include read more',
                                    'name' => 'content_readMore_include',
                                    'type' => 'true_false',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_100 PGN_acf_input_trueFalse',
                                        'id' => '',
                                    ),
                                    'column_width' => '100%',
                                    'message' => '',
                                    'default_value' => 0,
                                ),
                                array (
                                    'key' => 'field_switchContent_7',
                                    'label' => 'Text Content - Word Count - Desktop',
                                    'name' => 'content_wordCount_desktop',
                                    'type' => 'number',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '150',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'instructions' => 'Select the word count before the read more on desktop.',
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'field_switchContent_6',
                                                'operator' => '==',
                                                'value' => 1,
                                            ),
                                        ),
                                    ),
                                ),
                                array (
                                    'key' => 'field_switchContent_8',
                                    'label' => 'Text Content - Word Count - Tablet',
                                    'name' => 'content_wordCount_tablet',
                                    'type' => 'number',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '100',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'instructions' => 'Select the word count before the read more on tablet.',
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'field_switchContent_6',
                                                'operator' => '==',
                                                'value' => 1,
                                            ),
                                        ),
                                    ),
                                ),
                                array (
                                    'key' => 'field_switchContent_9',
                                    'label' => 'Text Content - Word Count - Mobile',
                                    'name' => 'content_wordCount_mobile',
                                    'type' => 'number',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '50',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'instructions' => 'Select the word count before the read more on mobile.',
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'field_switchContent_6',
                                                'operator' => '==',
                                                'value' => 1,
                                            ),
                                        ),
                                    ),
                                ),
                                array(
                                    'key' => 'field_switchContent_10',
                                    'label' => 'Text Content - Button Copy',
                                    'name' => 'content_button_copy',
                                    'type' => 'text',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_text',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'formatting' => 'html',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_switchContent_11',
                                    'label' => 'Text Content - Button Link',
                                    'name' => 'content_button_link',
                                    'type' => 'text',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_text',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'formatting' => 'html',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_switchContent_12',
                                    'label' => 'Text Content - Open in New Window',
                                    'name' => 'content_button_opensInNewWindow',
                                    'type' => 'true_false',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_trueFalse',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'message' => '',
                                    'default_value' => 0,
                                ),
                                array(
                                    'key' => 'field_switchContent_13',
                                    'label' => 'Carousel Items',
                                    'name' => 'switchContent_text_with_carousel_carousel_repeater',
                                    'type' => 'repeater',
                                    'sub_fields' => array (
                                        array (
                                            'key' => 'field_switchContent_14',
                                            'label' => 'Carousel Item - Type',
                                            'name' => 'carousel_item_type',
                                            'type' => 'select',
                                            'choices' => array (
                                                'profile_card' => 'Profile Card',
                                                'video' => 'Video',
                                            ),
                                            'default_value' => 'profile_card',
                                            'allow_null' => 0,
                                            'multiple' => 0,
                                            'column_width' => '100%',
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => 'PGN_acf_width_100 PGN_acf_input_select',
                                                'id' => '',
                                            ),
                                        ),
                                        array(
                                            'key' => 'field_switchContent_15',
                                            'label' => 'Carousel Item - Profile Image / Thumbnail',
                                            'name' => 'carousel_item_image',
                                            'type' => 'image',
                                            'column_width' => '50%',
                                            'save_format' => 'url',
                                            'preview_size' => 'thumbnail',
                                            'library' => 'all',
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => 'PGN_acf_width_50 PGN_acf_input_image',
                                                'id' => '',
                                            ),
                                        ),
                                        array(
                                            'key' => 'field_switchContent_16',
                                            'label' => 'Carousel Item - Video',
                                            'name' => 'carousel_item_media',
                                            'type' => 'file',
                                            'column_width' => '50%',
                                            'return_format' => 'url',
                                            'preview_size' => 'thumbnail',
                                            'library' => 'all',
                                            'mime_types' => '',
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => 'PGN_acf_width_50 PGN_acf_input_file',
                                                'id' => '',
                                            ),
                                            'conditional_logic' => array (
                                                array (
                                                    array (
                                                        'field' => 'field_switchContent_14',
                                                        'operator' => '==',
                                                        'value' => 'video',
                                                    ),
                                                ),
                                            ),
                                        ),
                                        array(
                                            'key' => 'field_switchContent_17',
                                            'label' => 'Carousel Item - Profile Type',
                                            'name' => 'carousel_item_profileType',
                                            'type' => 'text',
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                                'id' => '',
                                            ),
                                            'column_width' => '50%',
                                            'default_value' => '',
                                            'placeholder' => 'Please enter Profile Type here.',
                                            'prepend' => '',
                                            'append' => '',
                                            'formatting' => 'html',
                                            'maxlength' => '',
                                            'conditional_logic' => array (
                                                array (
                                                    array (
                                                        'field' => 'field_switchContent_14',
                                                        'operator' => '==',
                                                        'value' => 'profile_card',
                                                    ),
                                                ),
                                            ),
                                        ),
                                        array(
                                            'key' => 'field_switchContent_18',
                                            'label' => 'Carousel Item - Heading',
                                            'name' => 'carousel_item_heading',
                                            'type' => 'text',
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                                'id' => '',
                                            ),
                                            'column_width' => '50%',
                                            'default_value' => '',
                                            'placeholder' => 'Please enter heading here.',
                                            'prepend' => '',
                                            'append' => '',
                                            'formatting' => 'html',
                                            'maxlength' => '',
                                            'conditional_logic' => array (
                                                array (
                                                    array (
                                                        'field' => 'field_switchContent_14',
                                                        'operator' => '==',
                                                        'value' => 'profile_card',
                                                    ),
                                                ),
                                            ),
                                        ),
                                        array(
                                            'key' => 'field_switchContent_19',
                                            'label' => 'Carousel Item - Tag Line',
                                            'name' => 'carousel_item_tagLine',
                                            'type' => 'text',
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                                'id' => '',
                                            ),
                                            'column_width' => '50%',
                                            'default_value' => '',
                                            'placeholder' => 'Please enter tag line here.',
                                            'prepend' => '',
                                            'append' => '',
                                            'formatting' => 'html',
                                            'maxlength' => '',
                                            'conditional_logic' => array (
                                                array (
                                                    array (
                                                        'field' => 'field_switchContent_14',
                                                        'operator' => '==',
                                                        'value' => 'profile_card',
                                                    ),
                                                ),
                                            ),
                                        ),
                                        array(
                                            'key' => 'field_switchContent_20',
                                            'label' => 'Carousel Item - Categories',
                                            'name' => 'carousel_item_categories',
                                            'type' => 'textarea',
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                                'id' => '',
                                            ),
                                            'column_width' => '50%',
                                            'default_value' => '',
                                            'placeholder' => 'Please enter comma seperated categories here.',
                                            'prepend' => '',
                                            'append' => '',
                                            'formatting' => 'html',
                                            'maxlength' => '',
                                            'conditional_logic' => array (
                                                array (
                                                    array (
                                                        'field' => 'field_switchContent_14',
                                                        'operator' => '==',
                                                        'value' => 'profile_card',
                                                    ),
                                                ),
                                            ),
                                        ),


                                    ),
                                    'row_min' => '',
                                    'row_limit' => '',
                                    'layout' => 'block',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_100 PGN_acf_input_repeater',
                                        'id' => '',
                                    ),
                                    'button_label' => 'Add carousel item',
                                ),
                            ),
                            'row_min' => '',
                            'row_limit' => 2,
                            'layout' => 'block',
                            'button_label' => 'Add switch content item',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_repeater',
                                'id' => '',
                            ),
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_switchContent_1',
                                        'operator' => '==',
                                        'value' => 'text_with_carousel',
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
                /* scroll content module */
                array (
                    'label' => 'Scroll Content Module',
                    'name' => 'scrollContent_module',
                    'display' => 'block',
                    'min' => '',
                    'max' => '',
                    'sub_fields' => array(
                        array (
                            'key' => 'field_scrollContent_00',
                            'label' => 'Module - Add Custom ID',
                            'name' => 'customID_include',
                            'type' => 'true_false',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_trueFalse',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'message' => '',
                            'default_value' => 0,
                            'instructions' => 'Select to include a custom ID for this module.',
                        ),
                        array(
                            'key' => 'field_scrollContent_0',
                            'label' => 'Custom ID',
                            'name' => 'customID',
                            'type' => 'text',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                'id' => '',
                            ),
                            'column_width' => '50%',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '#',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                            'instructions' => 'Enter the custom ID name',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_scrollContent_00',
                                        'operator' => '==',
                                        'value' => 1,
                                    ),
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_scrollContent_1',
                            'label' => 'Scroll Conetent - Content Type',
                            'name' => 'scrollContent_type',
                            'type' => 'select',
                            'choices' => array (
                                'text_with_phoneImage' => 'Text Content with Phone Image',
                            ),
                            'default_value' => 'text_with_phoneImage',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'column_width' => '100%',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_select',
                                'id' => '',
                            ),
                        ),
                        array(
                            'key' => 'field_scrollContent_2',
                            'label' => 'Phone Image - Outer Image - Desktop',
                            'name' => 'scrollingContent_text_with_phoneImages_outerPhoneImage_desktop',
                            'type' => 'image',
                            'column_width' => '50%',
                            'save_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_image',
                                'id' => '',
                            ),
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_scrollContent_1',
                                        'operator' => '==',
                                        'value' => 'text_with_phoneImage',
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_scrollContent_3',
                            'label' => 'Phone Image - Outer Image - Mobile',
                            'name' => 'scrollingContent_text_with_phoneImages_outerPhoneImage_mobile',
                            'type' => 'image',
                            'column_width' => '50%',
                            'save_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_50 PGN_acf_input_image',
                                'id' => '',
                            ),
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_scrollContent_1',
                                        'operator' => '==',
                                        'value' => 'text_with_phoneImage',
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_scrollContent_4',
                            'label' => 'Scroll Content Items',
                            'name' => 'scrollingContent_text_with_phoneImages_content_repeater',
                            'type' => 'repeater',
                            'sub_fields' => array (
                                array (
                                    'key' => 'field_scrollContent_5',
                                    'label' => 'Text Content - include icon banner',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_icons_include',
                                    'type' => 'true_false',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_100 PGN_acf_input_trueFalse',
                                        'id' => '',
                                    ),
                                    'column_width' => '100%',
                                    'message' => '',
                                    'default_value' => 0,
                                ),
                                array(
                                    'key' => 'field_scrollContent_6',
                                    'label' => 'Text Content - Heading',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_heading',
                                    'type' => 'textarea',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                        'id' => '',
                                    ),
                                    'column_width' => '50%',
                                    'default_value' => '',
                                    'placeholder' => 'Please enter heading here.',
                                    'prepend' => '',
                                    'append' => '',
                                    'new_lines' => 'br',
                                    'formatting' => 'html',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_scrollContent_7',
                                    'label' => 'Text Content - Copy',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_copy',
                                    'type' => 'textarea',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_50 PGN_acf_input_text',
                                        'id' => '',
                                    ),
                                    'column_width' => '50%',
                                    'default_value' => '',
                                    'placeholder' => 'Please enter copy here.',
                                    'prepend' => '',
                                    'append' => '',
                                    'new_lines' => 'br',
                                    'formatting' => 'html',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_scrollContent_8',
                                    'label' => 'Text Content - include read more',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_copy_readMore_include',
                                    'type' => 'true_false',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_100 PGN_acf_input_trueFalse',
                                        'id' => '',
                                    ),
                                    'column_width' => '100%',
                                    'message' => '',
                                    'default_value' => 0,
                                ),
                                array (
                                    'key' => 'field_scrollContent_9',
                                    'label' => 'Text Content - Word Count - Desktop',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_wordCount_desktop',
                                    'type' => 'number',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '150',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'instructions' => 'Select the word count before the read more on desktop.',
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'field_scrollContent_8',
                                                'operator' => '==',
                                                'value' => 1,
                                            ),
                                        ),
                                    ),
                                ),
                                array (
                                    'key' => 'field_scrollContent_10',
                                    'label' => 'Text Content - Word Count - Tablet',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_wordCount_tablet',
                                    'type' => 'number',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '100',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'instructions' => 'Select the word count before the read more on tablet.',
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'field_scrollContent_8',
                                                'operator' => '==',
                                                'value' => 1,
                                            ),
                                        ),
                                    ),
                                ),
                                array (
                                    'key' => 'field_scrollContent_11',
                                    'label' => 'Text Content - Word Count - Mobile',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_wordCount_mobile',
                                    'type' => 'number',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_number',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '50',
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'instructions' => 'Select the word count before the read more on mobile.',
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'field_scrollContent_8',
                                                'operator' => '==',
                                                'value' => 1,
                                            ),
                                        ),
                                    ),
                                ),
                                array(
                                    'key' => 'field_scrollContent_12',
                                    'label' => 'Text Content - Button Copy',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_cta_copy',
                                    'type' => 'text',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_text',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'formatting' => 'html',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_scrollContent_13',
                                    'label' => 'Text Content - Button Link',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_cta_href',
                                    'type' => 'text',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_text',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'formatting' => 'html',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_scrollContent_14',
                                    'label' => 'Text Content - Open in New Window',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_cta_opensInNewWindow',
                                    'type' => 'true_false',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_trueFalse',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'message' => '',
                                    'default_value' => 0,
                                ),
                                array(
                                    'key' => 'field_scrollContent_15',
                                    'label' => 'Phone Image - Inner Image - Desktop',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_phone_image_desktop',
                                    'type' => 'image',
                                    'column_width' => '50%',
                                    'save_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_50 PGN_acf_input_image',
                                        'id' => '',
                                    ),
                                ),
                                array(
                                    'key' => 'field_scrollContent_16',
                                    'label' => 'Phone Image - Inner Image - Mobile',
                                    'name' => 'scrollingContent_text_with_phoneImages_content_phone_image_mobile',
                                    'type' => 'image',
                                    'column_width' => '50%',
                                    'save_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_50 PGN_acf_input_image',
                                        'id' => '',
                                    ),
                                ),
                            ),
                            'row_min' => '',
                            'row_limit' => '',
                            'layout' => 'block',
                            'button_label' => 'Add scroll content item',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_repeater',
                                'id' => '',
                            ),
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_scrollContent_1',
                                        'operator' => '==',
                                        'value' => 'text_with_phoneImage',
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_scrollContent_17',
                            'label' => 'Video Section - Heading',
                            'name' => 'scrollingContent_text_with_phoneImages_video_heading',
                            'type' => 'text',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_text',
                                'id' => '',
                            ),
                            'column_width' => '33%',
                            'default_value' => '',
                            'placeholder' => 'Please enter heading here.',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_scrollContent_1',
                                        'operator' => '==',
                                        'value' => 'text_with_phoneImage',
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_scrollContent_18',
                            'label' => 'Video Section - Video Thumbnail',
                            'name' => 'scrollingContent_text_with_phoneImages_video_poster',
                            'type' => 'image',
                            'column_width' => '33%',
                            'save_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_image',
                                'id' => '',
                            ),
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_scrollContent_1',
                                        'operator' => '==',
                                        'value' => 'text_with_phoneImage',
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_scrollContent_19',
                            'label' => 'Video Section - Video Source',
                            'name' => 'scrollingContent_text_with_phoneImages_video_source',
                            'type' => 'file',
                            'column_width' => '33%',
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'mime_types' => '',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_33 PGN_acf_input_file',
                                'id' => '',
                            ),
                            'conditional_logic' => array (
                                array (
                                    array (
                                        'field' => 'field_scrollContent_1',
                                        'operator' => '==',
                                        'value' => 'text_with_phoneImage',
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
                /* social feed module */
                array (
                    'label' => 'Social Feed Module',
                    'name' => 'social-feed',
                    'display' => 'block',
                    'min' => '',
                    'max' => '',
                    'sub_fields' => array(
                    ),
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'page',
            )
        ),
    ),
    'options' => array (
        'position' => 'normal',
        'layout' => 'no_box',
        'hide_on_screen' => array (

        ),
    ),
    'menu_order' => 1,
));





acf_add_options_page(array(
    'page_title' 	=> 'Theme General Settings',
    'menu_title'	=> 'Theme Settings',
    'menu_slug' 	=> 'theme-general-settings',
    'capability'	=> 'edit_posts',
    'redirect'		=> false
));

// acf_add_options_sub_page(array(
//     'page_title' 	=> 'Theme Header Settings',
//     'menu_title'	=> 'Header Options',
//     'parent_slug'	=> 'theme-general-settings',
// ));

// acf_add_options_sub_page(array(
//     'page_title' 	=> 'Theme Footer Settings',
//     'menu_title'	=> 'Footer Options',
//     'parent_slug'	=> 'theme-general-settings',
// ));


register_field_group(array (
    'id' => 'acf_page-builder-modules-footer',
    'title' => 'Page Builder Modules - Footer',
    'fields' => array (
        array (
            'key' => 'field_PBM_002',
            'label' => 'Page Builder Modules - Footer',
            'name' => 'page_builder_modules_footer',
            'type' => 'flexible_content',
            'layouts' => array (
                /* footer social menu */
                array (
                    'label' => 'Footer Menu - Social',
                    'name' => 'footer_socialMenu',
                    'display' => 'block',
                    'min' => '',
                    'max' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_footer_socialMenu_01',
                            'label' => 'Menu Items',
                            'name' => 'footer_socialMenu_repeater',
                            'type' => 'repeater',
                            'sub_fields' => array (
                                array(
                                    'key' => 'field_footer_socialMenu_02',
                                    'label' => 'Social Icon',
                                    'name' => 'socialIcon',
                                    'type' => 'image',
                                    'column_width' => '33%',
                                    'save_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_image',
                                        'id' => '',
                                    ),
                                ),
                                array(
                                    'key' => 'field_footer_socialMenu_03',
                                    'label' => 'Page URL',
                                    'name' => 'page_url',
                                    'type' => 'text',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_text',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'formatting' => 'html',
                                    'maxlength' => '',
                                ),
                                array (
                                    'key' => 'field_footer_socialMenu_04',
                                    'label' => 'Open Page in New Window?',
                                    'name' => 'openInNewWindow',
                                    'type' => 'true_false',
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => 'PGN_acf_width_33 PGN_acf_input_trueFalse',
                                        'id' => '',
                                    ),
                                    'column_width' => '33%',
                                    'message' => '',
                                    'default_value' => 0,
                                ),
                            ),
                            'row_min' => '',
                            'row_limit' => '',
                            'layout' => 'block',
                            'wrapper' => array (
                                'width' => '',
                                'class' => 'PGN_acf_width_100 PGN_acf_input_repeater',
                                'id' => '',
                            ),
                            'button_label' => 'Add social menu item'
                        ),
                    ),
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'theme-general-settings',
            )
        ),
    ),
    'options' => array (
        'position' => 'normal',
        'layout' => 'no_box',
        'hide_on_screen' => array (

        ),
    ),
    'menu_order' => 1,
));